name: ESPHome Build
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ESPHome 编译
        id: build_step
        uses: esphome/build-action@v7.0.0
        with:
          yaml-file: esp01.yaml
      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: esp-firmware
          path: ${{ steps.build_step.outputs.name }}/
