#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name:  MT7621

on:
  repository_dispatch:
  schedule:
    - cron: 0 20 * * 0
  watch:
    types: started
    
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'

env:
  DIY_P1_SH: deploy2.sh
  DIY_P2_SH: deploy2_D2.sh
  DIY_P3_SH: diy-part3.sh
  SSH_ACTIONS: true
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: 安装依赖包
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf wget curl swig rsync
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
    
    - name: 运行一键部署脚本
      run: |
        chmod +x $DIY_P1_SH
        ./$DIY_P1_SH
                    
    - name: 配置_脚本2
      run: |
        [ -e files ] && mv files openwrt/files
        chmod +x $DIY_P2_SH
        cd openwrt
        \cp -af ~/work/Actions-OpenWrt/Actions-OpenWrt/profile/config/AC2100_kernel.config .config
        ../$DIY_P2_SH
        
    - name: 定制_脚本3
      run: |
        chmod +x $DIY_P3_SH
        cd openwrt
        source $GITHUB_WORKSPACE/$DIY_P3_SH && Diy-Part1
        
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

    - name: 下载 package
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: 开始编译AC2100_kernel
      id: compile_1
      run: |
        cd openwrt
        make defconfig
        make -j$(nproc)
        
    - name: D2内核配置
      run: |
        cd openwrt
        git pull
        ./scripts/feeds update -a && ./scripts/feeds install -a
        \cp -af ~/work/Actions-OpenWrt/Actions-OpenWrt/profile/config/D2_kernel.config .config
        
    - name: 开始编译D2_kernel
      id: compile_2
      run: |
        cd openwrt
        make defconfig
        make -j$(nproc)
        
 
    - name: 开始拷贝固件
      id: Copy
      run: |
        mkdir ios
        cd ios
        cp -r ~/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/bin/targets/*/*/immortalwrt-ramips-mt7621-xiaomi_redmi-router-ac2100-initramfs-kernel.bin .
        cp -r ~/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/bin/targets/*/*/immortalwrt-ramips-mt7621-d-team_newifi-d2-initramfs-kernel.bin .
 
    - name: AC2100配置
      run: |
        cd openwrt
        git pull
        ./scripts/feeds update -a && ./scripts/feeds install -a
        \cp -af ~/work/Actions-OpenWrt/Actions-OpenWrt/profile/config/AC2100.config .config
 
    - name: 开始编译AC2100固件
      id: compile_3
      run: |
        cd openwrt
        make defconfig
        make -j$(nproc)
        
    - name: D2配置
      run: |
        cd openwrt
        git pull
        ./scripts/feeds update -a && ./scripts/feeds install -a
        \cp -af ~/work/Actions-OpenWrt/Actions-OpenWrt/profile/config/D2.config .config
 
    - name: 开始编译D2固件
      id: compile_4
      run: |
        cd openwrt
        make defconfig
        make -j$(nproc)

    - name: 开始拷贝固件
      id: Copy2
      run: |
        cd ios
        cp -r ~/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/bin/targets/*/*/immortalwrt-ramips-mt7621-xiaomi_redmi-router-ac2100-squashfs-sysupgrade.bin .
        cp -r ~/work/Actions-OpenWrt/Actions-OpenWrt/openwrt/bin/targets/*/*/immortalwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin .

    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        ls | grep -v .bin | xargs rm
        
    - name: 上传固件到WeTransfer
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wet -s -p 16 --no-progress ios/* | tee wetransfer.log
        ./transfer wet -s -p 16 --no-progress ios/*
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "::set-output name=url::$(cat wetransfer.log | grep https | cut -f3 -d" ")"  
