name: SSH-6h
on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4

      - name: Start SSH
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - name: Keep alive 6h
        run: sleep infinity
